### PR TITLE
[2024] TTtoXX_powheg-pythia8

### PR DESCRIPTION
**Pull request by sihyunjeon**

### CODE REVIEW

**Comment by sihyunjeon** [comment]
https://cms-pdmv-prod.web.cern.ch/mcm/requests?prepid=GEN-RunIII2024Summer24wmLHEGS-00001

**Comment by sihyunjeon** [comment]
https://cms-pdmv-prod.web.cern.ch/mcm/requests?prepid=GEN-RunIII2024Summer24wmLHEGS-00004

**Comment by sihyunjeon** [comment]
https://cms-pdmv-prod.web.cern.ch/mcm/requests?prepid=GEN-RunIII2024Summer24wmLHEGS-00006

**Comment by agrohsje** [comment]
we should fix all including the systematics, no ?

**Comment by sihyunjeon** [comment]
yes that will come later once we beef up the queue with DY and W first.
wee will make PR for the ones that are in McM, make another PR for another batch of things in McM, and so on, jsut to not lose track of what is done and what not

**Pull request merged**
