### PR TITLE
First commit - ggHHto4B template

### PR DESCRIPTION
**Pull request by mlizzo**
Hello, this is a draft PR based on the inputs shared by @sihyunjeon . As far as I understood, we (HIG MC contact) should try to integrate all HIG-marked samples from [this gsheet](https://docs.google.com/spreadsheets/d/1nyUnEG3EBAQRL5STTSaciVcPYvHYNEsLGTm2jSMVTh4/edit?gid=0#gid=0) into this repository. Since I am completely new to this workflow, this draft was made just to understand if the inputs are provided in the correct way. This PR is based on the ggHHto4B sample (line 79 of the gsheet) and I have used the corresponding Run3 [McM request](https://cms-pdmv-prod.web.cern.ch/mcm/requests?prepid=HIG-Run3Summer22EEwmLHEGS-01105&page=0&shown=127) as template. 

Please let me know if this is fine, if approved we will keep on adding other requests.
FYI: @Cvico @agrohsje

### CODE REVIEW

**Comment by sihyunjeon** [comment]
I think this is good to go in, @mlizzo do you have sth else in your mind? otherwise, please remove draft so that carlos or alexander can take a second look and merge it.

**Comment by sihyunjeon** [comment]
But I think you got the overall structure quite nicely

**Comment by agrohsje** [comment]
dear @mlizzo , do you mind posting the full powheg input card? you can also check from the powheg output if the cms card is not complete. 
i have two quick follow-ups. 
1.) why is cms higgs using mtop=173 instead of 172.5? asking in the context of harmonzing settings. 
2.) moreover i would encourage to remove this line:
            "'25:m0 = 125.0'",
the higgs is produced at lhe level, no need to specify the mass for pythia 8 .

**Comment by mlizzo** [comment]
Hi @agrohsje , of course! So the input card was sligthly adjusted based on the input as taken from this gridpack:

`/cvmfs/cms.cern.ch/phys_generator/gridpacks/RunIII/13p6TeV/slc7_amd64_gcc700/Powheg/V2/ggHH_slc7_amd64_gcc700_CMSSW_10_6_8_workdir3_ggHH_kl_0p00_kt_1p00_c2_0p00.tgz`

Here's the full card:

```
! ggHH production parameters:
mtdep 3
!                      1: Born improved HEFT
!                      2: approximated full theory (FTapprox)
!                      3: full theory

hmass 125            ! Higgs boson mass
topmass 173          ! top quark mass (THIS VALUE IS HARD CODED IN THE VIRTUAL
                     ! MATRIX ELEMENT AND FOR CONSISTENCY HAS NOT TO BE CHANGED WHEN
                     ! RUNNING FULL THEORY PREDICTIONS - i.e. mtdep 1
hdecaymode -1        ! PDG code for Higgs boson decay products (it affects only the SMC)
!                      allowed values are:
!                      0 all decay channels open
!                      1-6 d dbar, u ubar,..., t tbar (as in HERWIG)
!                      7-9 e+ e-, mu+ mu-, tau+ tau-
!                      10  W+W-
!                      11  ZZ
!                      12  gamma gamma
!                      -1  all decay channels closed

! Values of the Higgs couplings w.r.t SM
chhh      0.0       ! Trilinear Higgs self-coupling
ct        1.0       ! Top-Higgs Yukawa coupling
ctt       0.0       ! Two-top-two-Higgs (tthh) coupling
cggh      0.0       ! Effective gluon-gluon-Higgs coupling
cgghh     0.0       ! Effective two-gluon-two-Higgses coupling


! general parameters:
numevts NEVENTS
ih1         1        ! hadron 1 (1 for protons, -1 for antiprotons)
ih2         1        ! hadron 2 (1 for protons, -1 for antiprotons)
ebeam1 6800     ! energy of beam 1
ebeam2 6800    ! energy of beam 2
! To be set only if using LHA pdfs
lhans1 325300       ! pdf set for hadron 1 (LHA numbering)
lhans2 325300       ! pdf set for hadron 2 (LHA numbering)
! To be set only if using internal mlm pdf
# ndns1 131          ! pdf set for hadron 1 (mlm numbering)
# ndns2 131          ! pdf set for hadron 2 (mlm numbering)
! To be set only if using different pdf sets for the two incoming hadrons
! QCDLambda5 0.25    ! for not equal pdf sets

! Parameters to allow or not the use of stored data
use-old-grid    1    ! if 1 use old grid if file pwggrids.dat is present (<> 1 regenerate)
use-old-ubound  1    ! if 1 use norm of upper bounding function stored in pwgubound.dat, if present; <> 1 regenerate
!
ncall1  10000        ! number of calls for initializing the integration grid
itmx1       3        ! number of iterations for initializing the integration grid
ncall2  10000        ! number of calls for computing the integral and finding upper bound
itmx2       3        ! number of iterations for computing the integral and finding upper bound
foldcsi     1        ! number of folds on csi integration
foldy       1        ! number of folds on  y  integration
foldphi     1        ! number of folds on phi integration
nubound 15000        ! number of bbarra calls to setup norm of upper bounding function
# icsimax   1        ! <= 100, number of csi subdivision when computing the upper bounds
# iymax     1        ! <= 100, number of y subdivision when computing the upper bounds
# xupbound 2d0       ! increase upper bound for radiation generation


! OPTIONAL PARAMETERS

! scale settings:
#fixedscale   1      ! (dafault 0) fixed scale uses muren = mufac = 2*m_H
facscfact   1d0      ! (default 1d0) fac scale factor: mufact = muref * facscfact, muref=mHH/2
renscfact   1d0      ! (default 1d0) ren scale factor: muren  = muref * renscfact, muref=mHH/2

! Born, plots and powheg strategy:
bornonly          0  ! (default 0) if 1 do Born only
LOevents          0  !
#testplots 1
fastbtlbound      1  ! fast evaluation of Btilde upper bounds
storemintupb      1  ! store function calls in binary file for more precise generation
ubexcess_correct  1  ! corrects for error in upper bound estimate
#storeinfo_rwgt 0
compute_rwgt      0  ! store info to allow for reweighting
softtest          0  ! no check of the soft limit in the real
colltest          0  ! no check of the collinear limit in the real

! PARAMETERS needed for ggHH
hdamp           250

! PARAMETERS for parallel runnning
! - non parallel (for testing purposes only)
iseed SEED
#rand1     0         !  skipping  rand2*100000000+rand1 numbers.
#rand2     0         !  (see RM48 short writeup in CERNLIB)

! - parallel
#manyseeds 1
                     ! seeds in the same directory.
                     ! If set to 1, the program asks for an integer j;
                     ! The file pwgseeds.dat at line j is read, and the
                     ! integer at line j is used to initialize the random
                     ! sequence for the generation of the event.
                     ! The event file is called pwgevents-'j'.lhe
#parallelstage 4
#xgriditeration 1
maxseeds    9999

! PARAMETERS for reweighting
# rwl_file 'reweight_setup.xml'  https://github.com/alisw/POWHEG
# rwl_file         'pwg-rwl.dat'
# rwl_format_rwgt  1
# rwl_add          1
# rwl_group_events 2000
# lhapdf6maxsets 30


! PARAMETERS for Pythia8
#py8tune  xxx
#py8hepmc 1
#py8nohad 1
#py8nompi 1

check_bad_st1 1
check_bad_st2 1

withnegweights 1

pdfreweight 0
storeinfo_rwgt 0

rwl_group_events 2000
lhapdf6maxsets 50
rwl_file 'pwg-rwl.dat'
rwl_format_rwgt 1
```

I'm not sure if some gridpack specific settings are adjusted after the powheg script has run, if you spot something strange please let me know. About fragment settings, indeed I simply copied them fron the [original one](https://[cms-pdmv-prod.web.cern.ch/mcm/public/restapi/requests/get_fragment/HIG-Run3Summer22EEwmLHEGS-01105/0](https://cms-pdmv-prod.web.cern.ch/mcm/public/restapi/requests/get_fragment/HIG-Run3Summer22EEwmLHEGS-01105/0)) for reference, but you're right, the higgs mass doesn't matter at all - yet we keep having that setting in most of our HIG samples for some reason

**Comment by mlizzo** [comment]
I forgot to reply your first question, to be honest I don't know why `mtop 173` was chosen in the first place

**Comment by sihyunjeon** [comment]
i'll edit it, merge, and then see if we can make this process work in our machine.
let's tune the other parameters later (mt i will set it to 172.5 and then merge).

**Comment by agrohsje** [comment]
@sihyunjeon :
the name doesn't follow the convention it is 
GluGlutoHHto4B_Par-kl-0p00-kt-1p00-c2-0p00.json 
while for TOP we specified _powheg-pythia8: 
TTto2L2Nu_Hdamp-158_powheg-pythia8.json
Do we use g for photon and glu for gluons? 
I will write down the parameters that I spot in this and other requests so we can discuss with HIG.

**Pull request merged**
