### PR TITLE
adding DYto2E for POGs

### PR DESCRIPTION
**Pull request by agrohsje**
This is the ee analogon to DYto2Mu we already produced. vdecaymode is 1 for ee. Name ok? @sihyunjeon please check and merge. Thanks.

### CODE REVIEW

**Comment by sihyunjeon** [comment]
one question - do we produce separate decay modes now?
is it only for powheg or also for madgraph?

**Comment by agrohsje** [comment]
Generally I would say no. But here we deal with POG samples, so I would allow separate production. No one needs DY2Tau as far as I know.

**Comment by sihyunjeon** [comment]
@agrohsje Tau actually do have DY -> tau tau -> mu tauh requests

**Comment by agrohsje** [comment]
Powheg DY -> tau tau and then a particle filter ? Do you have the MCM link at hand ?

**Comment by agrohsje** [comment]
I would say if there is no special request from a POG/PAG to split or have a specific filter, I would produce l=e,mu,tau.

**Pull request merged**
