### PR TITLE
TT madgraphMLM

### PR DESCRIPTION
**Pull request by sihyunjeon**

### CODE REVIEW

**Comment by sihyunjeon** [comment]
@agrohsje I wonder if we can organize things like this (making pull request so that we can look at each other's cards)

**Comment by sihyunjeon** [comment]
also need to change the name

**Comment by agrohsje** [comment]
cards look modulo above comments good to me.

**Comment by sihyunjeon** [comment]
@agrohsje would be useful to ask genproductions reviewers to take a look as well at some point after we explain the philosophy and how it works just like we explained the genproductions review few weeks ago

**Comment by agrohsje** [comment]
why not. i mean a third pair of eyes doesn't hurt.

**Pull request closed without merging**
