### PR TITLE
VBF : ZtoXX-VBF_madgraph-pythia8

### PR DESCRIPTION
**Pull request by sihyunjeon**

### CODE REVIEW

**Comment by sihyunjeon** [comment]
should we write MJJ-150 so that in case somebody asks for sth like 100-150 we can be safe

**Comment by sihyunjeon** [comment]
after discussion, switch to mjj-120

**Comment by agrohsje** [comment]
@sihyunjeon : Will these samples be renamed according to what you proposed VBFto2L VBFto2Nu ?

**Comment by sihyunjeon** [comment]
Yes I just didn't have time to get back on this. Will do change

**Pull request merged**
