### PR TITLE
[2024] DYtoXX_powheg-pythia8

### PR DESCRIPTION
**Pull request by kkimeun**
rename gridpackfiles 
_MLL to _Bin-MLL

https://cms-pdmv-prod.web.cern.ch/mcm/requests?prepid=GEN-RunIII2024Summer24wmLHEGS*&dataset_name=DYto*&page=0&shown=127&limit=100

### CODE REVIEW

**Comment by sihyunjeon** [comment]
@agrohsje @Cvico

**Comment by sihyunjeon** [comment]
looks good to me, samples are renamed properly and all passed validation i'll send them to gen tmrw if nobody objects when i get up in the morning

**Comment by agrohsje** [comment]
Thanks for doing all the work. Are the names changed with a script? I went through the first changes but I get crazy to make sure - and _ are correct or not. 
@sihyunjeon what is now the final convention? What we have Bin in front of each cut? Can you post? And cuts are ordered alphabetically?

**Comment by sihyunjeon** [comment]
The name changes are done with a script yes

**Comment by sihyunjeon** [comment]
We do Bin Par Fil for headers

**Comment by sihyunjeon** [comment]
The cuts with bins come alphabetically

e.g.
Bin-HT-400to700-MLL-10to50-PTLL-50

**Comment by sihyunjeon** [comment]
The cuts with bins come alphabetically

e.g.
Bin-HT-400to700-MLL-10to50-PTLL-50

**Comment by agrohsje** [comment]
Ok. Then this should be ok.

**Comment by sihyunjeon** [comment]
> Ok. Then this should be ok.

I tried to make sure nothing is handcrafted in the middle 👻👻👻

**Pull request merged**
