### PR TITLE
GJ-4Jets_dRGJ-0p25

### PR DESCRIPTION
**Pull request by sihyunjeon**

### CODE REVIEW

**Comment by agrohsje** [comment]
stupid question: how did you decide the order of the cuts ? i mean in the name .

**Comment by sihyunjeon** [comment]
we didn't have a scheme,,,

for this though, dR is consistently given same for all samples and there will be no dR0p25to0p4, dR0p4to0p6 like samples so I put it in front PTG and HT i tried to make the branch go larger after each cuts.
PTG : 10-100, 100-200, 200
HT : 40-100, 100-200, 200-400, 400-600, ...

**Comment by agrohsje** [comment]
thanks. that makes a lot of sense. we should keep that in mind and ideally add to our rules.

**Comment by agrohsje** [comment]
in string order ?

**Comment by sihyunjeon** [comment]
i mean
PTG-10to100 - HT-40to100
PTG-10to100 - HT-100to200
PTG-10to100 - HT-200to400
PTG-10to100 - HT-400to700
PTG-10to100 - HT-700to1000
PTG-10to100 - HT-1000
PTG-100 - HT-40to100
PTG-100 - HT-100to200
PTG-100 - HT-200to400
PTG-100 - HT-400to700
PTG-100 - HT-700to1000
PTG-100 - HT-1000

**Comment by sihyunjeon** [comment]
is easier to see than

HT-40to100 - PTG-10to100
HT-40to100 - PTG-100
HT-100to200 - PTG-10to100
HT-100to200 - PTG-100
HT-200to400 - PTG-10to100
HT-200to400 - PTG-100
...

**Pull request merged**
