### PR TITLE
SingleT: TWminus_Hdamp* TWminus_MT TbarWplus_Hdamp* TbarWplus_MT

### PR DESCRIPTION
**Pull request by agrohsje**
adding systematic variations for single tW DR 
@sihyunjeon do you mind checking ?

### CODE REVIEW

**Comment by sihyunjeon** [comment]
TbarWplus LNu2Q - so this includes both "leptonic top + hadronic W" and "hadronic top + leptonic W"?

One physics question (but likely will be very small in impact), won't it be fair to scale the width according to the masses as well for top mass variation samples?

**Comment by agrohsje** [comment]
Indeed. So I am allowing all decays and then I am filtering with the OneLeptonFilter. IIRC, I saw reasonable BR's at some point. 

About the width. You are absolutely right. The point is that TOP PAG does mass scans independent of width scans and width scans independent of mass scans. So the width could also be 3.6 GeV which would point to some none-SM effects. Hence I kept the width constant.

**Comment by sihyunjeon** [comment]
Other than that looks good to me - feel free to merge

**Comment by agrohsje** [comment]
I would suggest that I submit the jobs first, then I make another PR for ttbar and tW fixing maxgamma. 
I also kept track of this via this issue: 
https://github.com/cms-PdmV/GridpackFiles/issues/68

**Comment by sihyunjeon** [comment]
ok. i was planning to do "grep mmaxgamma" in all cards and see if we have issues with anything that we were unaware of. but if you keep track it's fine.

**Pull request merged**
