### PR TITLE
add VBFH, ggFH 

### PR DESCRIPTION
**Pull request by yihui-lai**
based on genproductions/blob/master/bin/Powheg/production/Run3/13p6TeV/Higgs/HJ_MiNLO_NNLOPS_NNPDF31_13TeV/HJ_MiNLO_NNLOPS_NNPDF31_13TeV.input and genproductions/blob/master/bin/Powheg/production/Run3/13p6TeV/Higgs/VBF_H_NNPDF31_13TeV/VBF_H_NNPDF31_13p6TeV.input

### CODE REVIEW

**Comment by yihui-lai** [comment]
The ggF H card is based on https://github.com/cms-sw/genproductions/blob/master/bin/Powheg/production/Run3/13p6TeV/Higgs/HJ_MiNLO_NNLOPS_NNPDF31_13TeV/HJ_MiNLO_NNLOPS_NNPDF31_13TeV.input
```
numevts NEVENTS
ih1   1           ! hadron 1 (1 for protons, -1 for antiprotons)
ih2   1           ! hadron 2 (1 for protons, -1 for antiprotons)
ebeam1 6800d0      ! energy of beam 1
ebeam2 6800d0      ! energy of beam 2

hmass 125
hwidth 0.004221d0

hdecaywidth 0        ! If equals to 1 read total decay width from HDECAY sm.br2 file
                     ! if 0 the hwidth value is used


bwcutoff 15        ! how many W widths below and above the Higgs mass are included

! To be set only if using LHA pdfs
lhans1   325300      ! pdf set for hadron 1 (LHA numbering)
lhans2   325300     ! pdf set for hadron 2 (LHA numbering)

! Parameters to allow or not the use of stored data
use-old-grid    1 ! if 1 use old grid if file pwggrids.dat is present (<> 1 regenerate)
use-old-ubound  1 ! if 1 use norm of upper bounding function stored in pwgubound.dat, if present; <> 1 regenerate


ncall1   150000    ! number of calls for initializing the integration grid
itmx1    1        ! number of iterations for initializing the integration grid
ncall2   100000   ! number of calls for computing the integral and finding upper bound
itmx2    5        ! number of iterations for computing the integral and finding upper bound
fastbtlbound 1    ! (default 0) if 1 use fast btilde bound
storemintupb 1    ! store calls for grids
foldcsi   2       ! number of folds on csi integration
foldy     2       ! number of folds on  y  integration
foldphi   2       ! number of folds on phi integration
nubound 2000    ! number of bbarra calls to setup norm of upper bounding function

! OPTIONAL PARAMETERS

testplots  1       ! (default 0, do not) do NLO and PWHG distributions

withnegweights 1  ! (1 default) If 1 output negative weighted events.
                   ! If 0 descard them

renscfact  1d0   ! (default 1d0) ren scale factor: muren  = muref * renscfact 
facscfact  1d0   ! (default 1d0) fac scale factor: mufact = muref * facscfact 
pdfreweight 0       ! PDF reweighting

bornktmin 0.26    ! Minimum transverse momentum of the Higgs at the underlying Born level

minlo 1            ! default 0, set to 1 to use minlo

factsc2min 2       ! at this value the factorization scale is frozen (neede with minlo)

sudscalevar 1      ! (default 1) scale variation also in Sudakov form factors in minlo 

iseed    SEED       ! initialize random number sequence 

# variables for including quark mass effects
quarkmasseffects 1   ! Include quark mass effects
topmass 172.5d0      ! top quark mass (172.5 in HNNLO-patches/mdata.f)
bottommass 3.38d0    ! bottom quark mass in MSbar at MH
bmass_in_minlo 1     ! Include quark mass effects in Sudakov exponent
```
The VBF H card is based on https://github.com/cms-sw/genproductions/blob/master/bin/Powheg/production/Run3/13p6TeV/Higgs/VBF_H_NNPDF31_13TeV/VBF_H_NNPDF31_13p6TeV.input
```
numevts NEVENTS
ih1   1           ! hadron 1 (1 for protons, -1 for antiprotons)
ih2   1           ! hadron 2 (1 for protons, -1 for antiprotons)
ebeam1 6800d0     ! energy of beam 1
ebeam2 6800d0     ! energy of beam 2

lhans1  325300         ! pdf set for hadron 1 (LHA numbering)
lhans2  325300         ! pdf set for hadron 2 (LHA numbering)	

! Parameters to allow or not the use of stored data
use-old-grid    1 ! if 1 use old grid if file pwggrids.dat is present (<> 1 regenerate)
use-old-ubound  1 ! if 1 use norm of upper bounding function stored in pwgubound.dat, if present; <> 1 regenerate

ncall1 125000   ! number of calls for initializing the integration grid
itmx1  7    ! number of iterations for initializing the integration grid
ncall2 75000   ! number of calls for computing the integral and finding upper bound
itmx2  5    ! number of iterations for computing the integral and finding upper bound
foldcsi 2    ! number of folds on csi integration
foldy   5      ! number of folds on  y  integration
foldphi 2    ! number of folds on phi integration
nubound 175000 ! number of bbarra calls to setup norm of upper bounding function
icsimax  1     ! <= 100, number of csi subdivision when computing the upper bounds
iymax    1     ! <= 100, number of y subdivision when computing the upper bounds
xupbound 2d0   ! increase upper bound for radiation generation

! OPTIONAL PARAMETERS

renscfact  1d0   ! (default 1d0) ren scale factor: muren  = muref * renscfact
facscfact  1d0   ! (default 1d0) fac scale factor: mufact = muref * facscfact
withdamp    1      ! (default 0, do not use) use Born-zero damping factor
testplots  1      ! (default 0, do not) do NLO and PWHG distributions
#pdfreweight 0
#storeinfo_rwgt 0
#withnegweights 1 1 ! default 0,

iseed SEED

hmass    125d0       ! Higgs boson mass
hwidth   0.00407d0    ! Higgs boson width
hdecaymode -1   ! -1 no decay
                ! 0 all decay channels open
                ! 1-6 d dbar, u ubar,..., t tbar
                ! 7-9 e+ e-, mu+ mu-, tau+ tau-
                ! 10  W+W-
                ! 11  ZZ
                ! 12  gamma gamma

```

**Comment by yihui-lai** [comment]
Gridpacks with these inputs are: /cvmfs/cms.cern.ch/phys_generator/gridpacks/RunIII/13p6TeV/slc7_amd64_gcc10/Powheg/V2/HJ_slc7_amd64_gcc10_CMSSW_12_4_6_GluGluH.tgz and /cvmfs/cms.cern.ch/phys_generator/gridpacks/RunIII/13p6TeV/slc7_amd64_gcc700/Powheg/V2/VBF_H_slc7_amd64_gcc700_CMSSW_10_2_29_VBFHToBB.tgz

**Comment by agrohsje** [comment]
1.) pdfreweight 0 is centrally done, please remove:

# turn off obsolete stuff                                                                                            
sed -i "s/^pdfreweight.*/#pdfreweight 0/g" powheg.input
sed -i "s/^storeinfo_rwgt.*/#storeinfo_rwgt 0/g" powheg.input

2.) would you be ok with using the same b mass as in top: 5.06 GeV?  
we have two params so far: b mass and top mass. 

3.) can you check the original logs in the gridpack to see which other masses and model params are specified here.
in fact the model file above has settings that are more process specific. e.g. you might also want have alternative higgs masses. so it shouldn't be campaign but job dependent. that is the philosophy behind the split.
model parameters are all SM parameters (even the ones that we didn't pay attention to before) and in the json are the ones that are subject to "systematics".

**Comment by sihyunjeon** [comment]
> 2.) would you be ok with using the same b mass as in top: 5.06 GeV? we have two params so far: b mass and top mass.

I would be careful with this tho. we are using default mb in 4fs madgraph samples

**Comment by yihui-lai** [comment]
Thanks for the suggestions! 
(1) I removed pdfreweight from the inputs 
(2) I agree with SiHyun, the previous samples were using the 3.38 for b mass. But I am not sure if there's going to be a large effect by changing it to 5.06
(3) Indeed it would be good to move the Higgs mass and width from campaigns to cards, done

**Comment by yihui-lai** [comment]
(1) replace the minlo ggF H powheg samples with the normal NLO ggF H samples, as Mattia is working on adding the minlo samples all together. Input taken from https://github.com/cms-sw/genproductions/blob/master/bin/Powheg/production/Run3/13p6TeV/Higgs/gg_H_quark-mass-effects_NNPDF31_13p6TeV/gg_H_quark-mass-effects_NNPDF31_13p6TeV.input
(2) added VBF HH samples with HH decay to 4B and 2B2Tau

**Comment by sihyunjeon** [comment]
@agrohsje temporarily merging this to see if it's possible to make non minlo for higgs works or not

**Pull request merged**
