### PR TITLE
powheg qcd preparation

### PR DESCRIPTION
**Pull request by agrohsje**

### CODE REVIEW

**Comment by sihyunjeon** [comment]
hey, would it not be better to add the bias parameters?

**Comment by agrohsje** [comment]
@sihyunjeon @Cvico Please let me know in case you have comments. I am uncertain about the name. The request has 
   "bornktmin 5",
   "bornsuppfact 1500"
   Especially bornsuppfact could be very specific. Should we reflect in the name? Any proposal for a short string to add this? Let me know. I will probably not read Skype, but I will check here for feedback.

**Comment by sihyunjeon** [comment]
i think we should add it in the names. at least bias moduled sampleshould not take "QCD_powheg-pythia8" is what i am thinking. otherwise we lose the chance (if anybody wants one) of having normal qcd samples. can't we just follow the old namings?

**Comment by Cvico** [comment]
I agree it's better if we specify it in the name. What about BSF? 

- QCD-BSF1500_powheg-pythia8
- QCD-BornSupp1500_powheg-pythia8
- QCD-BornSuppression1500_powheg-pythia8

I don't have the old names at hand to check what was done in UL. But Since by itself the name of QCD_powheg-pythia8 is quite short, I think adding BornSuppression in someway would be better

**Comment by agrohsje** [comment]
I like QCD_BSF-1500_powheg-pythia8. Ok @sihyunjeon @Cvico ?

**Comment by sihyunjeon** [comment]
Hmmm I want to avoid using "B" solely followed by upper case letter for sake of bottom quarks. Not better to write "BornSF"?

**Pull request merged**
